spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5432/oauth2demo
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      leak-detection-threshold: 60000




  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: false
        jdbc.batch_size: 20
        order_inserts: true
        order_updates: true
        batch_versioned_data: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:your-email@gmail.com}
    password: ${MAIL_PASSWORD:your-app-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          connection timeout: 5000
          timeout: 3000
          write timeout: 5000

  cache:
    type: redis
    redis:
      time-to-live: 3600000 # 1 hour

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2000ms
      database: 0
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

  jackson:
    default-property-inclusion: non_null
    serialization.write-dates-as-timestamps: false
    deserialization.fail-on-unknown-properties: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


logging:
  level:
    com:
      sultonbek1547:
        oauth2demo:
          config:
            JwtAuthenticationFilter: DEBUG
          "": DEBUG


server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /
  error:
    include-stacktrace: never
    include-message: always
    include-binding-errors: always


springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    display-request-duration: true
    groups-order: desc
    operations-sorter: method
    disable-swagger-default-url: true
    use-root-path: true

---

---

